version: '3.8'

services:
  api:
    build:
     context: .  # Path to your Dockerfile
     dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    expose:
      - "8000"
    mem_limit: 512m
    cpus: 0.5
