# Generated by Django 6.1 on 2026-08-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_slug_alter_product_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='diety',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='dieties', to='products.category'),
        ),
    ]
