HOME_PAGE_POPULAR_MOORTI_BLOCK = "popular_moorti"
HOME_PAGE_POPULAR_MOORTI_BLOCK_TITLE = "Popular Moorti"

HOME_PAGE_DREAM_MOORTI_BLOCK = "shop_by_dream_moorti"
HOME_PAGE_DREAM_MOORTI_BLOCK_TITLE = "Shop by Dream Moorti"

HOME_PAGE_DREAM_TEMPLES_BLOCK = "dream_temples"
HOME_PAGE_DREAM_TEMPLES_BLOCK_TITLE = "Dream Temples"

HOME_PAGE_CATEGORIES_BLOCK = "shop_by_categories"
HOME_PAGE_CATEGORIES_BLOCK_TITLE = "Shop by Categories"

HOME_PAGE_HOME_DECORS_BLOCK = "shop_home_decors"
HOME_PAGE_HOME_DECORS_BLOCK_TITLE = "Shop Home Decors"

HOME_PAGE_REVIEWS_BLOCK = "reviews"
HOME_PAGE_REVIEWS_BLOCK_TITLE = "Testimonials"
