AVAILABILITY_IN_STOCK = "In Stock"
AVAILABILITY_MADE_TO_ORDER = "Made To Order"
AVAILABILITY_OUT_OF_STOCK = "Out Of Stock"

AVAILABILITY_CHOICES = [
    AVAILABILITY_IN_STOCK,
    AVAILABILITY_MADE_TO_ORDER,
    AVAILABILITY_OUT_OF_STOCK,
]